#! bin/bash
# Copyright Joe Maples <frap129@gmail.com> (c) 2015

# Unset variables that will be used
unset PFLAG
unset VFLAG
unset MFLAG
unset DIRPATH

# Check for first argument
if [ -z "$1" ]; then
  if [ "$1" == "-p*" ]; then
    PFLAG=$1;
  elif [ "$1" == "-v*" ]; then
    VFLAG=$1;
  elif [ "$1" == "-m*" ]; then
    MFLAG=$1;
  else
    DIRPATH=$1;
  fi
fi;

# Check for second argument
if [ -z "$2" ]; then
  if [ "$2" == "-p*" ]; then
    PFLAG=$2;
  elif [ "$2" == "-v*" ]; then
    VFLAG=$2;
  elif [ "$2" == "-m*" ]; then
    MFLAG=$2;
  else
    DIRPATH=$2;
  fi
fi;

# Check for third argument
if [ -z "$3" ]; then
  if [ "$3" == "-p*" ]; then
    PFLAG=$3;
  elif [ "$3" == "-v*" ]; then
    VFLAG=$3;
  elif [ "$3" == "-m*" ]; then
    MFLAG=$3;
  else
    DIRPATH=$3;
  fi
fi;

# Check for foruth arument
if [ -z "$4" ]; then
  if [ "$4" == "-p*" ]; then
    PFLAG=$4;
  elif [ "$4" == "-v*" ]; then
    VFLAG=$4;
  elif [ "$4" == "-m*" ]; then
    MFLAG=$4;
  else
    DIRPATH=$4;
  fi
fi;

# Make sure DIRPATH is set
if [ -z "$DIRPATH" ]; then
  echo "Usage: mkcd [-p -v -m] directory_name";
  exit 1;
fi;

# Execute command
mkdir $PFLAG $VFLAG $MFLAG $DIRPATH && cd $DIRPATH;
